[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --filter @wacent/worker..."]

[phases.build]
cmds = ["pnpm --filter @wacent/worker build"]

[start]
cmd = "pnpm --filter @wacent/worker start"
